### ISSUE TITLE
Add the reviews functionality

### ISSUE THREAD

**Issue by prosper74** [prosper74/Go-real-estate-app#2]
The task is to create the reviews functionality. 
- There is currently a reviews section in the single property page. Add a form for user to add reviews
- There should be a star rating functionality ( 5 star maximum)
- Show only 5 reviews and a button to load more reviews (Pagination would be better)
- Add the backend handler, route and postgres function
- Make sure every reviews is authenticated
- List the user reviews in the user's dashboard review tab

**Comment by Yuroq** [comment]
Hey, do you still need help with this?

**Comment by prosper74** [comment]
> Hey, do you still need help with this?

Yes please

**Comment by Yuroq** [comment]
> > Hey, do you still need help with this?
> 
> Yes please
Sounds good, I'm having trouble starting the project up I ran npm install in the front-end and npm run dev then I got an error.

**Comment by Yuroq** [comment]
This is the error: 
Error: connect ECONNREFUSED ::1:80

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
error: connect ECONNREFUSED : (1:80)
<unknown> (Error: connect ECONNREFUSED
: (1:80)

**Comment by prosper74** [comment]
This indicates that you have not setup the backend.

The backend is written Go. Check the readme file for instructions.

If you still can't set it up, let me know

**Comment by Yuroq** [comment]
Sounds good, does the feature have to be written in TS or is it fine if I write it in Reactjs?

**Comment by prosper74** [comment]
Typescript preferable

**Comment by prosper74** [comment]
Feature added
